[package]
name = "show-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
indicatif = "0.18.3"
ordered-float = "5.1.0"
petgraph = "0.8.3"
rand = "0.9.2"
russcip = { version = "0.9.1", features = ["from-source"] }
